default: &default

  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *default
  database: rustedrails_development

test:
  <<: *default
  database: rustedrails_test

production:
  <<: *default
  database: rustedrails_production
  password: <%= ENV['RUSTEDRAILS_DATABASE_PASSWORD'] %>
